### ISSUE TITLE
P_R '-om' default is set agressively and does not match Olimex default

### ISSUE THREAD

**Issue by chili-chips-ba** [chili-chips-ba/openCologne#35]
@pu-cc what's the rationale behind setting the `-om` P_R default to the highest possible supply voltage? Note that Olimex board defaults to midpoint. That's a recipe for problems.

Please, help us also understand the implications of the P_R `-tm` option, as well as its interplay with the -om.

__________
>![CologneChip P_R Default](https://github.com/user-attachments/assets/43b5f3e7-8346-4511-b341-4aae35518586)
>![Olimex-VDD_CORE_SET-Jumper](https://github.com/user-attachments/assets/24a9ab84-8fdb-4a06-90ce-1eba944a50aa)
>![Olimex-Default](https://github.com/user-attachments/assets/7b2eaf24-6fd8-45e0-a410-0e018dd21dfe)

**Comment by pu-cc** [comment]
> what's the rationale behind setting the `-om` P_R default to the highest possible supply voltage?

It gives a good understanding what the design can achieve in best case (1.1V) and the worst conditions.

> Please, help us also understand the implications of the P_R `-tm` option, as well as its interplay with the `-om`.

With `-om`, you specify the core voltage:

- 1: lowpower (0.9V)
- 2: economy (1.0V)
- 3: speed (1.1V)

In addition, the corner/conditions `-tm` can be specified, as this also has an effect on the timing:

- 1: fast corner, 125°C
- 2: typical corner, 25°C
- 3: worst corner, -40°C (default)

As far as i know, tools usually output their timings as "worst conditions".
