### ISSUE TITLE
Can the QSPI pins and ConfigFlash be repurposed for User App?!

### ISSUE THREAD

**Issue by chili-chips-ba** [chili-chips-ba/openCologne#39]
Would it be possible to, upon loading FPGA bitfile from ConfigFlash:
  1) Take over the corresponding FPGA pins and use them for other things?
          - possibly even allowing user access to the hardened QSPI controller within FPGA
  2) Use the Flash for app data storage
  
GateMate datasheet does not seem to be listing those options.
> ![image](https://github.com/user-attachments/assets/a67f4f7f-a663-45f0-ae17-4e2bf8fc45b4)

Yes, we love to be uber-efficient (don't call us stingy 😉) and get extra mileage from Olimex-provided components.
> ![image](https://github.com/user-attachments/assets/e2c9f820-a045-494c-b85d-279894385ccd)

**Comment by pu-cc** [comment]
> Take over the corresponding FPGA pins and use them for other things?

Yes, that is f course possible. The data sheet does contain information about this on page 84, using the `uCIO` parameter.

![image](https://github.com/user-attachments/assets/3ad4ec9e-1f66-4ea1-be3b-0d17df0340dd)

Even the example CCF contains the config pins, which can all be used by setting the `uCIO` parameter.
https://colognechip.com/downloads/ccgm1a1-evb-master.ccf

> possibly even allowing user access to the hardened QSPI controller within FPGA

The hardened QSPI controller is used exclusively for configuration.

> Use the Flash for app data storage

This follows from 1. that this is of course possible, too.

**Comment by chili-chips-ba** [comment]
Thank you, this is very informative. 

Closing this question with a note that it would help to add a reference or link to the `-uCIO` tool option in the Config section of the datasheet.
