### ISSUE TITLE
GateMate pre-packaged downloader does not work with Olimex board

### ISSUE THREAD

**Issue by chili-chips-ba** [chili-chips-ba/openCologne#7]
openFPGAloader that's packaged with GateMate toolsuite (see https://www.colognechip.com/docs/ug1002-toolchain-install-latest.pdf) does not work for Olimex. We had to alter the published procedure and download it from other repo.

@goran-mahovlic and @aimamovic6 can provide additional details...

**Comment by pu-cc** [comment]
Which version are you referring to? openFPGALoader has had support for the Olimex board for some time, see here:

- https://github.com/trabucayre/openFPGALoader/pull/388/commits/18056180a8c5a9d3c944b203a5bdf5d3dfed9732
- https://github.com/trabucayre/openFPGALoader/commit/bcbd8aa0e34a52293511a52fbb459ca043d7b134

The current pre-packed version is v.0.12.1 and therefore contains all the necessary support. Of course, you must specify the correct board (`-b olimex_gatemateevb`) in the Makefile. What exactly went wrong?

**Comment by goran-mahovlic** [comment]
@pu-cc Tnx Patric, you are right there version is up to date. 

I am also using openFPGALoader v0.12.1 without problems.

Problem we had is that your build is not working on our systems. 

It is working once we compile from source.

![image](https://github.com/chili-chips-ba/openCologne/assets/4248736/f6e609fd-aaa9-4893-9615-01d09ae50d72)

**Comment by pu-cc** [comment]
Unfortunately, it is never possible to compile compatible binaries for all Linux distributions and all versions.

A workaround, as you already found out and as it is also described in [UG1002](https://www.colognechip.com/docs/ug1002-toolchain-install-latest.pdf), is to compile it from source.
May I ask on which Debian version you are having the issue with? Did you install `libhidapi` with apt?
